version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      - MARIADB_PASSWORD=my_password

  myapp:
    tty: true
    image: 'bitnami/laravel:latest'
    labels:
      kompose.service.type: nodeport
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=my_password
    depends_on:
      - mariadb
    ports:
      - 4001:3000
    volumes:
      - ./:/app
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
